### ISSUE TITLE
在MAC上显示有些问题

### ISSUE THREAD

**Issue by cseroad** [pureqh/Hyacinth#1]
<img width="991" alt="image" src="https://github.com/pureqh/Hyacinth/assets/59865739/4fdde74c-7ee0-4be9-a958-6b492aba89ca">

**Comment by pureqh** [comment]
这个问题已知 可能是我jkd版本太低了

**Comment by cseroad** [comment]
<img width="861" alt="image" src="https://github.com/pureqh/Hyacinth/assets/59865739/d50270eb-0a70-4485-b2c1-cc6a6167ce4f">

显示存在S2-017漏洞存在！！，未找到编号

**Comment by cseroad** [comment]
<img width="921" alt="image" src="https://github.com/pureqh/Hyacinth/assets/59865739/5ab7a808-5e03-46a3-ab20-be8008d987d8">

命令回显也有些问题

**Comment by cseroad** [comment]
> 这个问题已知 可能是我jkd版本太低了

windows上显示没问题

**Comment by pureqh** [comment]
命令回显是编码问题 这个可以手动改

**Comment by cseroad** [comment]
> 命令回显是编码问题 这个可以手动改

我的意思是回显不完整

**Comment by pureqh** [comment]
马上修复

**Comment by cseroad** [comment]
> 马上修复

期待师傅大作
