### ISSUE TITLE
struts2框架漏洞检测不精准

### ISSUE THREAD

**Issue by Superhero-zero** [pureqh/Hyacinth#2]
使用vulhub启用了s2-046靶场后，工具无法探测出来漏洞
![image](https://github.com/pureqh/Hyacinth/assets/66772820/afcd93eb-9fd6-4841-b665-9a6468fc56cb)

同时给师傅提个建议，出一个清空日志按钮。

**Comment by pureqh** [comment]
好的我去看一下 清空日志的话 每次点击检测都会自动清空日志&nbsp;&nbsp;


清辉
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月22日(星期五) 上午9:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [pureqh/Hyacinth] struts2框架漏洞检测不精准 (Issue #2)





 
使用vulhub启用了s2-046靶场后，工具无法探测出来漏洞
 
 
同时给师傅提个建议，出一个清空日志按钮。

**Comment by pureqh** [comment]
我这边试了一下可以检出
![image](https://github.com/pureqh/Hyacinth/assets/45117428/693fb38f-9c1b-4fda-b252-e23ed01fd2ce)
046要找到对应action

**Comment by Superhero-zero** [comment]
> 我这边试了一下可以检出 ![image](https://user-images.githubusercontent.com/45117428/269807382-693fb38f-9c1b-4fda-b252-e23ed01fd2ce.png) 046要找到对应action

能执行命令么  我执行命令没反应

**Comment by Superhero-zero** [comment]
而且重复点击检测后 日志那没有任何 反应 这边是使用java8去执行的

**Comment by pureqh** [comment]
使用代理模式可以执行成功 这里应该是payload没同步

**Comment by Superhero-zero** [comment]
> 使用代理模式可以执行成功 这里应该是payload没同步

这个命令无回显问题能否在下个版本更新解决

**Comment by pureqh** [comment]
可以
