### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Rubi1iXD** [pureqh/Hyacinth#3]
哥，那个fastjson的dnslog一直用不了怎么回事啊，换了几个平台了。

**Comment by pureqh** [comment]
要用https://github.com/lanyi1998/DNSlog-GO 项目 配置类似
![image](https://github.com/pureqh/Hyacinth/assets/45117428/fbf92acf-81b6-469d-be23-dd8dad5482ad)

**Comment by Rubi1iXD** [comment]
好的，谢谢大哥！

**Comment by Rubi1iXD** [comment]
> 要用https://github.com/lanyi1998/DNSlog-GO 项目 配置类似 ![image](https://user-images.githubusercontent.com/45117428/270221809-fbf92acf-81b6-469d-be23-dd8dad5482ad.png)
