### ISSUE TITLE
这么神奇?百度

### ISSUE THREAD

**Issue by MInggongK** [pureqh/Hyacinth#5]
![dsf](https://github.com/user-attachments/assets/6e4cb385-7339-4316-9b72-805c16b6d10e)

![dfsd](https://github.com/user-attachments/assets/70b59f97-4ebc-4bbf-975e-50624453a8e8)

**Comment by MInggongK** [comment]
![dsfsf](https://github.com/user-attachments/assets/86f6e3cd-9e8c-4d08-a09d-3c62aa795ae4)

**Comment by pureqh** [comment]
用的时候麻烦看下说明
![image](https://github.com/user-attachments/assets/ad3a3365-9db4-4401-9f9e-e637318d46df)

**Comment by MInggongK** [comment]
第二个key,第三个key也是这样啊
![fdg](https://github.com/user-attachments/assets/91705dce-d87f-4bd6-86ae-970a3474c27c)
![fgdg](https://github.com/user-attachments/assets/9045cb43-3600-44df-971f-e7724917adcd)
